runtime: nodejs18
service: shortly-team4-frontend

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|ico|json|txt))$
    static_files: build/\1
    upload: build/.*\.(gif|png|jpg|css|js|ico|json|txt)$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301
